Update test-app browser targets from latest ember-cli blueprint (#941)
Believe this configuration is pretty stale and no longer necessary.

Resolves ember-try test builds failing with ember-source > 5.0.0.

> not ok 1 Chrome 113.0 - [undefined ms] - Global error: Uncaught TypeError: (0 , _emberBabel.extends) is not a function at http://localhost:7357/assets/vendor.js, line 12297

Error output looks similar to emberjs/ember.js/issues/20281 so I'm linking here in case it helps other trace this issue.